### ISSUE TITLE
BUG: Default placement results in error

### ISSUE THREAD

**Issue by krechtern** [tonysamperi/ngx-float-ui#12]
When I don't provide the `placement` input the library throws an error:

<img width="678" alt="image" src="https://github.com/tonysamperi/ngx-float-ui/assets/6142193/850836ae-84c4-4398-9e78-c1b5cb2fe690">

When I add the default `'auto'` placement via input, then the error is gone.

**Expected behavior**
I expect that I don't have to provide the input, when I want to use the default placement.

**Desktop (if execution):**
 - OS: macOS 14.2.1
 - Browser: Chrome 121.0.6167.139

** Versions
 - ngx-float-ui version 17.1.0
 - @angular/core version 17.1.1
 - typescript version 5.3.3

**Comment by tonysamperi** [comment]
You're right, it should default to auto. Fixing ASAP.

**Comment by tonysamperi** [comment]
Fixed in v 17.1.0

**Comment by krechtern** [comment]
Sorry to comment on a closed issue. I just updated the library to 17.1.1 and I still face the same issue. If I don't provide any placement the error mentioned above is still thrown.

**Comment by tonysamperi** [comment]
> Sorry to comment on a closed issue. I just updated the library to 17.1.1 and I still face the same issue. If I don't provide any placement the error mentioned above is still thrown.

No worries man. Can you create a blitz?
There's a good starter...here

**Comment by krechtern** [comment]
Sure! Here you go: https://stackblitz.com/edit/ts-angular-16-float-ui-wpur2k?file=package.json

Just hover over the visible container.

**Comment by tonysamperi** [comment]
Ok I get it. Fixing ASAP.

**Comment by tonysamperi** [comment]
Fixed for real in v17.1.2 and v16.0.2
